version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - static-files:/app/static
    networks:
      - my-network

  db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - my-network

volumes:
  static-files:
  postgres-data:
  redis-data:

networks:
  my-network: